### ISSUE TITLE
有遇到过卡顿的问题吗

### ISSUE THREAD

**Issue by channingbox** [Wyf841015/JLLTIPTV#5]
你有遇到过卡顿的问题吗，是网络的问题还是软件缓存播放机制的问题，我是用安卓手机mx player看的，你试过用什么软件看。

**Comment by Wyf841015** [comment]
手机卡一般是手机性能问题



---原始邮件---
发件人: "channingbox"<notifications@github.com&gt;
发送时间: 2019年11月18日(星期一) 上午8:21
收件人: "Wyf841015/JLLTIPTV"<JLLTIPTV@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Wyf841015/JLLTIPTV] 有遇到过卡顿的问题吗 (#5)



你有遇到过卡顿的问题吗，是网络的问题还是软件缓存播放机制的问题，我是用安卓手机mx player看的，你试过用什么软件看。

**Comment by channingbox** [comment]
你用什么软件看的，不卡吗？？？

**Comment by channingbox** [comment]
> 手机卡一般是手机性能问题
> […](#)
> ---原始邮件--- 发件人: "channingbox"<notifications@github.com&gt; 发送时间: 2019年11月18日(星期一) 上午8:21 收件人: "Wyf841015/JLLTIPTV"<JLLTIPTV@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Wyf841015/JLLTIPTV] 有遇到过卡顿的问题吗 (#5) 你有遇到过卡顿的问题吗，是网络的问题还是软件缓存播放机制的问题，我是用安卓手机mx player看的，你试过用什么软件看。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你用什么软件看的，不卡？？？

**Comment by Wyf841015** [comment]
我基本不看，看也是电视看，电视上的直播软件都可以



---原始邮件---
发件人: "channingbox"<notifications@github.com&gt;
发送时间: 2019年11月18日(星期一) 上午8:34
收件人: "Wyf841015/JLLTIPTV"<JLLTIPTV@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Wyf841015"<64652178@qq.com&gt;;
主题: Re: [Wyf841015/JLLTIPTV] 有遇到过卡顿的问题吗 (#5)


 
手机卡一般是手机性能问题
 …
 ---原始邮件--- 发件人: "channingbox"<notifications@github.com&gt; 发送时间: 2019年11月18日(星期一) 上午8:21 收件人: "Wyf841015/JLLTIPTV"<JLLTIPTV@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Wyf841015/JLLTIPTV] 有遇到过卡顿的问题吗 (#5) 你有遇到过卡顿的问题吗，是网络的问题还是软件缓存播放机制的问题，我是用安卓手机mx player看的，你试过用什么软件看。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你用什么软件看的，不卡？？？

**Comment by Wyf841015** [comment]
我用盒子看不卡，用计算机看高清画面抖，感觉是计算机性能不足



---原始邮件---
发件人: "channingbox"<notifications@github.com&gt;
发送时间: 2019年11月18日(星期一) 上午8:34
收件人: "Wyf841015/JLLTIPTV"<JLLTIPTV@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Wyf841015"<64652178@qq.com&gt;;
主题: Re: [Wyf841015/JLLTIPTV] 有遇到过卡顿的问题吗 (#5)


 
手机卡一般是手机性能问题
 …
 ---原始邮件--- 发件人: "channingbox"<notifications@github.com&gt; 发送时间: 2019年11月18日(星期一) 上午8:21 收件人: "Wyf841015/JLLTIPTV"<JLLTIPTV@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Wyf841015/JLLTIPTV] 有遇到过卡顿的问题吗 (#5) 你有遇到过卡顿的问题吗，是网络的问题还是软件缓存播放机制的问题，我是用安卓手机mx player看的，你试过用什么软件看。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你用什么软件看的，不卡？？？

**Comment by channingbox** [comment]
我也不是卡，就是隔一会就有马赛克
